### ISSUE TITLE
Congratulations first and my first bug

### ISSUE THREAD

**Issue by azulforblue** [sillsdev/web-scriptureforge#118] opened 2015-01-27 15:18 UTC
Undefined index: name line 86 /var/www/languageforge.org/htdocs/models/languageforge/lexicon/commands/LexProjectCommands.php 
 line , f->lex_import_lift(Array)

JsonRpcServer.php line 67, call_user_func_array(Array, Array)

api.php line 23, JsonRpcServer::handle(Sf, CI_Output)

![bichito](https://cloud.githubusercontent.com/assets/10727044/5920872/23af9408-a640-11e4-9905-e4aa1a39d7b3.png)

**Comment by azulforblue** [comment] 2015-01-27 15:21
![bichito](https://cloud.githubusercontent.com/assets/10727044/5920907/6da5476a-a640-11e4-9f74-0f04975615ce.png)
This happened next and I show you the size of my LIFT file down there.

Have a nice day,

**Comment by megahirt** [comment] 2015-02-10 06:49
duplicate of sillsdev/web-scriptureforge#119

**Closed by megahirt** 2015-02-10 06:49 UTC
