### ISSUE TITLE
Lift Import into language forge

### ISSUE THREAD

**Issue by kentschroeder** [sillsdev/web-scriptureforge#116] opened 2015-01-13 08:12 UTC
I got  this error when import a lift file into my project for this first time.  the lift file was generated by FLEx 8.

Undefined index: name line 86 /var/www/languageforge.org/htdocs/models/languageforge/lexicon/commands/LexProjectCommands.php 
 line , f->lex_import_lift(Array)

JsonRpcServer.php line 67, call_user_func_array(Array, Array)

api.php line 23, JsonRpcServer::handle(Sf, CI_Output)

**Comment by kentschroeder** [comment] 2015-01-19 06:52
I still have this problem.  I can not go further until it is resolved

**Comment by megahirt** [comment] 2015-02-10 06:51
closed as duplicate of sillsdev/web-scriptureforge#117

**Closed by megahirt** 2015-02-10 06:51 UTC
